# Generated by Django 2.2 on 2019-06-03 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('indy_community', '0009_auto_20190430_0331'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceivedProof',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proof_data', models.TextField(blank=True, max_length=4000)),
                ('verified', models.BooleanField(default=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indy_community.AgentConnection')),
                ('proof_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indy_community.IndyProofRequest')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indy_community.AgentConversation')),
            ],
        ),
        migrations.CreateModel(
            name='IssuedCredential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential_data', models.TextField(max_length=4000)),
                ('credential_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indy_community.IndySchema')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indy_community.AgentConnection')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indy_community.AgentConversation')),
            ],
        ),
    ]
