# Generated by Django 2.2 on 2019-06-03 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indy_community', '0009_auto_20190430_0331'),
        ('ubc_lab4', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivedproof',
            name='proof_type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='indy_community.IndyProofRequest'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='receivedproof',
            name='proof_data',
            field=models.TextField(blank=True, max_length=4000),
        ),
    ]
